language: "rust"
cache: "cargo"
rust:
  - 1.36.0
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add rustfmt
  - |
      if [ "$TRAVIS_RUST_VERSION" != "1.36.0" ]; then
        rustup component add clippy
      fi
  - |
      if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
        cargo install --force cargo-audit
      fi
  - cargo generate-lockfile
script:
  - |
      if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
        cargo audit
      fi
  - cargo fmt -- --check
  - |
      if [ "$TRAVIS_RUST_VERSION" != "1.36.0" ]; then
        cargo clippy --all-targets --all-features -- -D warnings
      fi
  - cargo build --verbose
  - cargo test --verbose
if: "type != push OR (tag IS blank AND branch = master)"
notifications:
  email: false
  irc:
    channels:
      - secure: "WtuFMaASfrKlPbXWg7cAzxTLSggrix/jqizB3bdGbZTWg8MR0qoa90U9St6h5ELWMc+7mQjJSky0/KXD9BOVLSlok8E12xb8H5soPMW6GjYAek4+JzUeXPYSKNYkP29ZQc26Z9P9TyN/WvJoXIQbaWfMoPmr/g3Rn4z5PyeQgp1+AC54w5zLPtLLjh+WHPYhRoCT7iAsYlx0UazEw3i+aGyN+UdogimDD9ISUKFHOWyXJGyBzFxSpAYaRESnT4I0rJo6ETBkUbEopXvTRyClOsgEk1HRb82+kVNqkampeSDZyb2aCGLbRESd16xVbcE5J2HYu59p5zc00PINMf2nApDEkN/RHERZ4w9lMaxi/fH1TMQZwoNPEd/5n1EU/SLjKi7o/kLdTKEcZyTMd7IZA+TqXjFhKHQlYouOEv742TcWz3jg5+AEhKqjkcpDZTEuNHyMAS4onHg1M9pK2rVh3xmVQ1V2iYM8yY2+73SefJzigkhtXwgnJEv6fJc8IFSPOHtEUBx2KkZps6sRwUxVz5zMgV+4t1h9l4Mt8wOSojoKSxgtAhsHj8pqPysT7vUJPhY6hzzW2nhVHd8IUt49xRNktUr9s+B7yS1Up6+84GTmPmR3lUa+dbZ1PaI2K8VVyctiA4tbkk/n+EFqXL9FY2Gh8XbaWnb7fpWHrJRuZL4="
    use_notice: true
